services:
  api:
    build:
      context: .
      target: development
    command: pnpm run start:dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/nest-blog
      - MONGODB_URI=mongodb://mongodb:27017/nest-blog
    volumes:
      - .:/usr/src/app

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nest-blog
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data: 
  mongodb_data:
