# .github/workflows/local-ci.yml

name: Deploy with Docker Compose

# This pipeline triggers on every push to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  deploy-job:
    # This job runs on your self-hosted runner (your server)
    runs-on: self-hosted

    steps:
      # 1. Checks out the repository code to the runner's workspace.
      # This is useful for the workflow's context but we won't use this checkout directly.
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Pulls the latest code into your ACTUAL project directory on the server.
      - name: Pull latest code in project directory
        run: |
          echo "Navigating to project directory..."
          # --- IMPORTANT ---
          # Make sure this is the correct path to your project on the server
          cd /home/ubuntu/nestBlogApi
          
          echo "Pulling latest changes from main branch..."
          git pull origin main

      # 3. Rebuilds and restarts the services using Docker Compose. 🚀
      - name: Rebuild and Restart Docker Compose Services
        run: |
          echo "Starting Docker Compose..."
          # Navigate to the project directory where your docker-compose.yml is located
          cd /home/ubuntu/nestBlogApi
          
          # This command will:
          #   up: Start the services
          #   -d: Run in detached mode (in the background)
          #   --build: Rebuild the images if the source code or Dockerfile has changed
          docker-compose up -d --build

      # 4. (Optional but Recommended) Clean up old, unused Docker images. 🧹
      - name: Clean up old docker images
        run: |
          docker image prune -af