# .github/workflows/local-ci.yml

name: Local CI Pipeline Test

# This pipeline triggers on every push to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  test-runner-job:
    # IMPORTANT: This tells GitHub to send this job to your local runner
    runs-on: self-hosted

    steps:
      # 1. Checks out your repository code onto your local machine
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Creates an empty file named test.txt
      - name: Create a test file
        run: touch test.txt

